#!/usr/bin/env python3
"""Ask GPT-5 for design recommendation on G1 Hallucination Prevention."""

from assertion_analyzer.config import call_gpt5_api

prompt = """We are designing an assertion framework for evaluating Workback Plans (WBP) generated by an AI assistant. We need your expert opinion on a design decision.

## Current Framework Design

We have two layers:
- **S (Structural) Dimensions (S1-S20)**: Check IF something exists in the response
  - S1: Meeting Title
  - S2: Timeline Alignment
  - S3: Ownership Assignment
  - S4: Participant Identification
  - S5: Task Dates
  - S6: Dependencies & Blockers
  - S8: Task Descriptions
  - etc.

- **G (Grounding) Dimensions (G1-G10)**: Check if VALUES match the source scenario
  - G1: Hallucination Prevention (currently)
  - G2: Attendee Grounding (names match source)
  - G3: Date/Time Grounding (dates match source)
  - G4: Artifact Grounding (files match source)
  - G5: Topic Grounding (topics match source)
  - G6: Action Item Grounding (tasks match source)
  - G7: Role Grounding (roles match source)
  - G8: Constraint Grounding (limits match source)
  - G9: Planner-Generated Consistency
  - G10: Relation Grounding (relationships match source)

## Design Principle
Every G assertion MUST have an S parent:
- S checks IF something exists
- G checks if the VALUE/IDENTITY matches the source

Example: "The response should assign Tisa as owner for confirming agenda"
- S3 (Ownership Assignment): Response should have an owner assignment
- G2 (Attendee Grounding): Owner name must be "Tisa"
- G6 (Action Item Grounding): Task must be "confirming agenda"

## The Question: What about G1 (Hallucination Prevention)?

**Option A: Keep G1 as a grounding dimension**
- G1 is used alongside other Gs under an S parent
- Example: S4 + G2 (attendees) + G1 (no additional attendees)
- Pro: Consistent with S→G pattern
- Con: G1 is different - it's a constraint, not a value to match

**Option B: Make Hallucination an S-level assertion**
- Create a new S dimension: "No Hallucination" or "Factual Accuracy"
- This S assertion, when evaluated, checks ALL G dimensions (G2-G10)
- Remove G1 from grounding dimensions
- Pro: Cleaner separation - S = structure, G = grounding values only
- Con: This S dimension is "meta" - it's about the whole response

**Option C: Something else?**

Please analyze both options and recommend the best approach for a clean, consistent framework design. Consider:
1. Conceptual clarity
2. Practical implementation
3. Edge cases
4. Evaluation workflow
"""

print("Asking GPT-5 for design recommendation...")
result = call_gpt5_api(prompt, temperature=0.3, max_tokens=2000)
print(result)
